# This is a basic workflow to help you get started with Actions

name: Terraform init

# Controls when the workflow will run
on:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  init:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID : ${{ secrets.AZURE_CLIENT_ID }} 
      ARM_CLIENT_SECRET : ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRPTION_ID : ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: hashicrop/setup-terraform@03
      - run: terraform init

     
